### ISSUE TITLE
ThingMagic M5E

### ISSUE THREAD

**Issue by 7ry4641n** [paulvha/ThingMagic#9]
Hello. I am trying to connect ThingMagic M5E-C to HW-UART ESP32 using your library but nothing works for me. I connected the M5E using a voltage divider on the TX line. I use stable 5V power from the power supply. But I keep getting "Module failed to respond. Please check wiring" message. Could you help me? This is for my university project.

**Comment by paulvha** [comment]
HI
Not sure this library is compatible with an M5E. Have not tried or studied that before.  BUT maybe...
How did you connect the hardware? (pictures ?)
you could turn on debug in the sketch and see what messages you get.

regards,
Paul
regards,
Paul

**Comment by 7ry4641n** [comment]
Thanks for your reply! Getting with debug:
```
try to connect to RFID reader
sendCommand: 
 [FF] [00] [03] [1D] [0C]
Time out 1: No response from module
Try reset RFID speed
sendCommand: 
 [FF] [04] [06] [00] [00] [96] [00] [E0] [41]
Time out 1: No response from module
```
![1](https://user-images.githubusercontent.com/37774538/162965220-0371f516-857b-417b-b65c-b3aa012261c3.jpeg)

![2](https://user-images.githubusercontent.com/37774538/162965239-4ef9e583-0aed-4bae-9a55-5753e0cf78dc.jpeg)

**Comment by paulvha** [comment]
The library is sending request for hardware and software level but does not get an answer. I'll try-out to find m5e info this evening. . Not sture what it expects.

Regards
Paul

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by 7ry4641n** [comment]
Thanks a lot. [Here's Developer’s Guide for M5E](https://www.graftek.com.tr/dosya/m5efamilydevguide-may11-pdf/838/)
As I assume the problem is in different codes. I think to start the firmware I need to send the code 0xFF,0x00,0x04,0x1D,0x0B. I read it in the guide. Could you add M5E support to your library?

**Comment by paulvha** [comment]
Thanks

I looked at the documentation and photos.

In the developers guide, page 65.. I see the same FF 00 03 1D 0C request for the M5E.  So maybe still a cable / connection issue
Where did you find 0xFF,0x00,0x04,0x1D,0x0B ??

Can not find information about the connection details to the M5E itself. Do you have that?

Looking at the pictures (hard to see) BUT is the 5K resistor connected to the same place as the 10K and yellow wire ??

regards,
Paul

________________________________
Van: 7ry4641n ***@***.***>
Verzonden: dinsdag 12 april 2022 15:17
Aan: paulvha/ThingMagic ***@***.***>
CC: paulvha ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [paulvha/ThingMagic] ThingMagic M5E (Issue #9)


Thanks a lot. Here's Developer’s Guide for M5E<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.graftek.com.tr%2Fdosya%2Fm5efamilydevguide-may11-pdf%2F838%2F&data=04%7C01%7C%7C3bc905bbb3eb474c2e1108da1c86cc5b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637853662521300186%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Zp1xDsKBx6dgiOAz0HcoJOscmYuPSjBz2%2FEgpft88yI%3D&reserved=0>
As I assume the problem is in different codes. I think to start the firmware I need to send the code 0xFF,0x00,0x04,0x1D,0x0B. I read it in the guide. Could you add M5E support to your library?

**Comment by 7ry4641n** [comment]
> is the 5K resistor connected to the same place as the 10K and yellow wire ??

Yes that's right. Something is wrong?

**Comment by paulvha** [comment]
could not clearly see from the picture, but that is good and correct.
Are you using serial2 ? which sketch do you use ? 
As mentioned earlier, I could not find info about the M5E connector. Have you double checked that it is connected to the right points ? What are the other connector point for ?

Maybe one more point. Do you have a USB to Serial convertor. if so connect the M5E to a PC and downlaod the Universal Reader Assistent (URA) from Jadak. Then you can test whether it works. Also it allows to create a communication log file to see what information is exchanged .


Regards,
Paul

**Comment by paulvha** [comment]
With respect to the M5E connector, found that information and looks to be connected correctly.

Another test you can try: make a simple sketch to write something to the serial port and read from the serial port. Then connect RX and TX from the ESP32 together and check that you get the same data in return. 

Also I have validated in the source of the MercuryAPI that the command for requesting the version info is the same between the M6E and M5E.

regards,
Paul

**Comment by 7ry4641n** [comment]
> could not clearly see from the picture, but that is good and correct. Are you using serial2 ? which sketch do you use ? As mentioned earlier, I could not find info about the M5E connector. Have you double checked that it is connected to the right points ? What are the other connector point for ?

Sure, I'm using Serial2. ESP32 RFID Server sketch. 

![Безымянный](https://user-images.githubusercontent.com/37774538/163126695-d2b97d28-91c0-46c8-b33a-9645ceedf039.png)
![Безымянный1](https://user-images.githubusercontent.com/37774538/163126760-bb2d6236-5c1f-47f9-a15a-a4454d290e92.png)

> Maybe one more point. Do you have a USB to Serial convertor. if so connect the M5E to a PC and downlaod the Universal Reader Assistent (URA) from Jadak. Then you can test whether it works. Also it allows to create a communication log file to see what information is exchanged .

I can not download URA, the site is not responding. Can you send me the x64 version?

**Comment by 7ry4641n** [comment]
> Another test you can try: make a simple sketch to write something to the serial port and read from the serial port. Then connect RX and TX from the ESP32 together and check that you get the same data in return.

I'll try to test it now

**Comment by paulvha** [comment]
drop me an email paulvha@hotmail.com and I will send you the URA..
Also see the other remarks that I have made in the meantime.

regards
Paul

**Comment by 7ry4641n** [comment]
Thanks to Paul, we figured out what was going on. So the problem was that, by default, M5e waits for a command at 9600 baud after power is applied, so it did not understand the command. Also, to start the reader, you need to additionally send the following command to it to start the firmware before configuring the device: `0xFF,0x00,0x04,0x1D,0x0B`
Hopefully @paulvha will someday add M5e support to the Sparkfun library to make things easier for newbies :)
